package com.youngrich.oliveold.domain;

public enum CategoryDetailName {
    // 스킨케어
    SKIN_TONER(1), ESSENCE_SERUM_AMPULE(1), CREAM(1), LOTION(1), MIST_OIL(1), SKINCARE_SET(1),

    // 마스크팩
    SHEET_PACK(2), PAD_PACK(2), FACIAL_PACK(2), NOSE_PACK(2), PATCH(2),

    // 클렌징
    CLEANSING_FOAM_GEL(3), CLEANSING_OIL_BALM(3), CLEANSING_WATER_MILK(3), PEELING_SCRUB(3), CLEANSING_TISSUE_PAD(3), LIP_EYE_REMOVER(3),

    // 선케어
    SUNCREAM(4), SUNSTICK(4), SUNCUSHION(4), SUNSPRAY_PATCH(4), TANNING_AFTER_SUN(4),

    // 메이크업
    LIP_MAKEUP(5), BASE_MAKEUP(5), EYE_MAKEUP(5),

    // 뷰티소품
    MAKEUP_TOOLS(6), SKINCARE_TOOLS(6), EYE_TOOLS(6), HAIR_BODY_TOOLS(6), GUASHA_NAIL_TOOLS(6), BEAUTY_DEVICES(6), BEAUTY_ACCESSORIES(6),

    // 더모코스메틱
    DERMATOLOGICAL_SKINCARE(7), DERMATOLOGICAL_BODYCARE(7), DERMATOLOGICAL_CLEANSING(7), DERMATOLOGICAL_SUNCARE(7), DERMATOLOGICAL_MASK(7),

    // 맨즈케어
    MEN_SKINCARE(8), MEN_MAKEUP(8), MEN_SHAVING(8), MEN_HAIRCARE(8), MEN_BODYCARE(8), MEN_FRAGRANCE_LIFE(8),

    // 헤어케어
    SHAMPOO_CONDITIONER(9), TREATMENT_PACK(9), HAIR_ESSENCE(9), HAIR_DYE_PERM(9), HAIR_TOOLS_BRUSH(9), HAIR_STYLING(9),

    // 바디케어
    BODY_LOTION_OIL(10), SHOWER_BATH(10), LIP_CARE(10), HAND_CARE(10), BODY_MIST(10), HAIR_REMOVAL_WAXING(10), DEODORANT(10), GIFT_SET(10), BABY_PRODUCTS(10),

    // 향수/디퓨저
    WOMEN_FRAGRANCE(11), MEN_FRAGRANCE(11), UNISEX_FRAGRANCE(11), MINI_SOLID_FRAGRANCE(11), HOME_FRAGRANCE(11),

    // 네일
    REGULAR_NAIL(12), GEL_NAIL(12), NAIL_TIP_STICKER(12), NAIL_CARE(12);

    private final int parentId;

    CategoryDetailName(int parentId) {
        this.parentId = parentId;
    }

    public int getParentId() {
        return parentId;
    }
}